### ISSUE TITLE
Supporting Groovy junit tests

### ISSUE THREAD

**Issue by codemomentum** [febeling/lein-junit#16]
Background: I am rewriting a project in Clojure but i really dont want to migrate the test suite which is written in Groovy. Also, i believe groovy unit tests are not that uncommon and brings great deal of flexibility when compared with Java.

Do you think this is a feature worth integrating?

**Comment by febeling** [comment]
I don't think this feature would fit in here well. Groovy support likely deserves a separate package. Please reopen if I miss something.
