### ISSUE TITLE
Loosen or change lein-junit.test.core wrt "Suppressed exit"

### ISSUE THREAD

**Issue by laurentpetit** [febeling/lein-junit#20]
Hello,

Starting with Leiningen 2.4.0, when leiningen.core.main/*exit-process?* is set to false, it will not be possible to rely on the thrown exception message to be hardcoded to the value "Suppressed exit".
Checking the ex-data :exit-code will be the way to ensure it's a suppressed exit, and the exception message may or may not be "Suppressed exit" (when invoked via leiningen.core.main/abort, it will be the message passed as an argument).

My suggestion is to either totally remove the 3 lines where the message content is checked, or to change the checked message to be the underlying message sent via abort, where it makes sense.

**Comment by febeling** [comment]
Thanks for the info, 1479b593ee4a6d3ac57aed27dd80f29eba68d425 fixes the failures. I see this just now. Sorry about the delay.
