### ISSUE TITLE
Test file detection pattern should be an option

### ISSUE THREAD

**Issue by sertel** [febeling/lein-junit#24]
Currently it is hardcoded as #".*Test\.java" in core./find-testcases. It would be really great if this could be specified as an option. So the implementation of the function could be simply changed to this:
```clojure
(defn find-testcases
  "Returns the class filesnames of the project's Junit test cases."
  [project]
  (for [path (:junit project)
        file (file-seq (file (:root project) path))
        :when (and (not (.isDirectory file))
                   (re-matches (:junit-test-file-pattern project #".*Test\.java") (str file)))]
    (-> (replace (str file) File/separatorChar \/)
        (replace (re-pattern (str ".*/" path "/")) "")
        (replace #"\.java" ".class"))))
```
leaving the normal option as the default.

**Comment by sertel** [comment]
Hi,

I implemented the change on a fork of the master branch. Can you please verify it and migrate it into the master?

Thanks,
Sebastian

**Comment by febeling** [comment]
I was just looking at this :) That looks reasonable. Would you mind sending a pull request along?

**Comment by sertel** [comment]
Hhmm, the Travis build failed but not with my test case as far as I can see. All tests are passing for me locally.

The output:

    lein test lein-junit.test.core
    Compiling 3 source files to /home/travis/build/febeling/lein-junit/sample/target/classes
    Test com.example.SubscriptionTest FAILED
    JUnit tests failed.
    lein test :only lein-junit.test.core/test-junit
    FAIL in (test-junit) (core.clj:83)
    expected: (= "Suppressed exit" (.getMessage e))
      actual: (not (= "Suppressed exit" "JUnit tests failed."))
    lein test :only lein-junit.test.core/test-junit
    FAIL in (test-junit) (core.clj:84)
    expected: (= {:exit-code 1} (.getData e))
      actual: (not (= {:exit-code 1} {:exit-code 1, :suppress-msg false}))
    Test com.example.SubscriptionTest FAILED
    JUnit tests failed.
    lein test :only lein-junit.test.core/test-junit
    FAIL in (test-junit) (core.clj:89)
    expected: (= "Suppressed exit" (.getMessage e))
      actual: (not (= "Suppressed exit" "JUnit tests failed."))
    lein test :only lein-junit.test.core/test-junit
    FAIL in (test-junit) (core.clj:90)
    expected: (= {:exit-code 1} (.getData e))
      actual: (not (= {:exit-code 1} {:exit-code 1, :suppress-msg false}))
    Ran 10 tests containing 52 assertions.
    4 failures, 0 errors.
    Tests failed.
    Tests failed.
    The command "lein2 test" exited with 1.

Seems like the problem is that ```clojure.lang.ExceptionInfo/getMessage``` has changed.

**Comment by febeling** [comment]
Yes, it's got to do with technomancy/leiningen#1437. 

I fixed it and push in a minute. I would be good if you could rebase then.

**Comment by sertel** [comment]
Will do.

**Comment by tkruse** [comment]
Hi, can you tell me how that would help me to run all junit tests *except* for those name ```*AbstractTest.java```. Because abstract classes fail when run as tests. Or how else could i achieve that?

**Comment by sertel** [comment]
Hi,
well after all the evaluation uses a regular expression. So you could just check here to lern how to exclude certain patterns: http://fineonly.com/solutions/regex-exclude-a-string
I suppose in your case you would write something like
```
^(.(?!Abstract))*$
```
You will still have to enhance this pattern to match everything that matches your test file name pattern.

I hope this helps.

Cheers,
Sebastian

**Comment by tkruse** [comment]
Thanks for the reply, that's what I feared. I confirm it works for me using:
```
(defproject ...
  :junit-test-file-pattern #"^((?!Abstract).)*Test.java$"
```
