### ISSUE TITLE
An error message about leinigen.hooks.junit is shown

### ISSUE THREAD

**Issue by jmao** [febeling/lein-junit#6]
When I run lein junit or lein test, there is an error message like this

Error: cannot resolve leiningen.hooks.junit/activate hook

shown before any test runs, although the junit tests run successfully.

**Comment by scarytom** [comment]
I'm using lein-junit 1.1.8 and I'm still getting this:
```
% lein deps
Warning: implicit hook found: lein-junit.plugin/hooks 
Hooks are deprecated and will be removed in a future version.
```
Am I doing something wrong @r0man ?

**Comment by r0man** [comment]
@scarytom No, this is a warning from the latest Leiningen saying that things will change around hooks. I have seen this with other plugins as well. I have't investigated what the proper migration path is yet.

**Comment by scarytom** [comment]
Oh, right. Thanks @r0man. Should I raise a new issue for this?

**Comment by r0man** [comment]
@scarytom Yes, open an issue so it does not get lost.
