### ISSUE TITLE
The test code is compiled before clojure code

### ISSUE THREAD

**Issue by jmao** [febeling/lein-junit#7]
In my project, I want to use lein-junit to test my clojure code, however it requires adding test code to java-source-paths, which causes compilation failure for me.  It would be helpful if lein-junit reads test source path from a different keyword, such as junit-source-paths, so that leiningen does not compile test/java before compiling clojure code.

**Comment by febeling** [comment]
Inactive, so I'm closing. Please reopen if this is still an issue.
